version: '3'
services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - '3031:3031'
    environment:
      MONGO_URI: mongodb://mongo:27017/task-manager
      PORT: 3031
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0.27
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
