version: '3'
services:
    backend:
        build:
            context: ./backend
        volumes:
            - ./backend:/app
        ports:
            - '3000:3000'
        environment:
            MONGO_URI: mongodb://mongo:27017/task-manager
        command: npm run dev

    mongo:
        image: mongo:5.0.27
        ports:
            - '27017:27017'
        volumes:
            - mongo-data:/data/db

volumes:
    mongo-data:
